import streamlit as st
import io
from datetime import date

def generate_pdf(u):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1.5*cm, bottomMargin=1.5*cm,
                                leftMargin=2*cm, rightMargin=2*cm)

        title_style = ParagraphStyle("T", fontSize=26, textColor=colors.HexColor("#00ffe7"),
                                     alignment=TA_CENTER, spaceAfter=4, fontName="Helvetica-Bold")
        sub_style = ParagraphStyle("S", fontSize=10, textColor=colors.HexColor("#5a7a99"),
                                   alignment=TA_CENTER, spaceAfter=16)
        heading_style = ParagraphStyle("H", fontSize=12, textColor=colors.HexColor("#00ffe7"),
                                       spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold")
        body_style = ParagraphStyle("B", fontSize=10, textColor=colors.HexColor("#333"), spaceAfter=4)
        disc_style = ParagraphStyle("D", fontSize=8, textColor=colors.HexColor("#999"),
                                    alignment=TA_CENTER, spaceBefore=10)

        story = []
        story.append(Paragraph("⚡ FITAI PRO — HEALTH REPORT", title_style))
        story.append(Paragraph(
            f"Generated: {date.today().strftime('%d %B %Y')}  ·  {u.get('name','User').upper()}  ·  BSc Data Science Project",
            sub_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#00ffe7")))
        story.append(Spacer(1, 0.4*cm))

        def make_table(data):
            t = Table(data, colWidths=[3.5*cm, 6*cm, 3.5*cm, 5*cm])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0,0),(0,-1), colors.HexColor("#e8f4f8")),
                ("BACKGROUND", (2,0),(2,-1), colors.HexColor("#e8f4f8")),
                ("FONTNAME", (0,0),(-1,-1), "Helvetica"),
                ("FONTSIZE", (0,0),(-1,-1), 9),
                ("GRID", (0,0),(-1,-1), 0.5, colors.HexColor("#ddd")),
                ("PADDING", (0,0),(-1,-1), 6),
                ("VALIGN", (0,0),(-1,-1), "MIDDLE"),
            ]))
            return t

        story.append(Paragraph("PERSONAL PROFILE", heading_style))
        story.append(make_table([
            ["Name", u.get("name","—"), "Age", str(u.get("age","—"))],
            ["Gender", u.get("gender","—"), "Weight", f"{u.get('weight','—')} kg"],
            ["Height", f"{u.get('height','—')} cm", "Goal", u.get("goal","—")],
            ["Activity", u.get("activity_level","—"), "Experience", u.get("fitness_experience","—")],
        ]))

        story.append(Paragraph("HEALTH METRICS", heading_style))
        story.append(make_table([
            ["BMI", str(u.get("bmi","—")), "BMI Category", u.get("bmi_category","—")],
            ["BMR", f"{u.get('bmr','—')} kcal/day", "TDEE", f"{u.get('tdee','—')} kcal/day"],
            ["Fitness Score", f"{u.get('fitness_score','—')}/100", "Injury Risk", u.get("injury_risk","—")],
            ["Workout Level", u.get("workout_level","—"), "Diet Calories", f"{u.get('diet_calories','—')} kcal"],
        ]))

        story.append(Paragraph("ML MODEL SUMMARY", heading_style))
        story.append(Paragraph(
            f"Workout Level predicted using <b>Random Forest Classifier</b> (100 estimators, sklearn). "
            f"Result: <b>{u.get('workout_level','—')}</b>.", body_style))
        story.append(Paragraph(
            f"Injury Risk assessed using <b>Logistic Regression</b> (multinomial). "
            f"Result: <b>{u.get('injury_risk','—')} Risk</b>.", body_style))
        story.append(Paragraph(
            f"BMR calculated using <b>Mifflin-St Jeor Equation</b>. "
            f"TDEE adjusted for activity level.", body_style))

        story.append(Spacer(1, 1*cm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#ddd")))
        story.append(Paragraph(
            "This report is generated by an AI system for academic purposes. "
            "Always consult a qualified healthcare professional before starting any fitness or dietary programme. "
            "FitAI Pro · BSc Data Science · University of Mumbai",
            disc_style))

        doc.build(story)
        buffer.seek(0)
        return buffer
    except ImportError:
        return None

def show():
    st.markdown("""
    <div style="margin-bottom:2rem;">
        <div style="color:#5a7a99; font-size:0.7rem; letter-spacing:3px; text-transform:uppercase;">Module 07 · reportlab</div>
        <div style="font-family:'Orbitron',monospace; font-size:1.5rem; color:white; font-weight:700; margin-top:0.3rem;">
            PDF HEALTH REPORT
        </div>
        <div style="color:#5a7a99; font-size:0.82rem; margin-top:0.3rem;">
            Export your complete health assessment as a professional PDF document
        </div>
    </div>
    """, unsafe_allow_html=True)

    if not st.session_state.user_data:
        st.warning("⚠️ Complete Profile Setup first.")
        return

    u = st.session_state.user_data

    # Summary cards
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("BMI", u.get("bmi","—"), u.get("bmi_category",""))
    c2.metric("Fitness Score", f"{u.get('fitness_score','—')}/100")
    c3.metric("Injury Risk", u.get("injury_risk","—"))
    c4.metric("Workout Level", u.get("workout_level","—"))

    st.markdown("<br>", unsafe_allow_html=True)

    st.markdown("""
    <div class="ai-card">
        <div style="color:#5a7a99; font-size:0.7rem; letter-spacing:3px; text-transform:uppercase; margin-bottom:1rem;">
            Report Contents
        </div>
        <div style="display:grid; grid-template-columns:1fr 1fr; gap:0.6rem;">
            <div style="color:#c8d8f0; font-size:0.82rem;">✅ Personal profile & biometrics</div>
            <div style="color:#c8d8f0; font-size:0.82rem;">✅ BMI, BMR & TDEE calculations</div>
            <div style="color:#c8d8f0; font-size:0.82rem;">✅ AI fitness score (weighted formula)</div>
            <div style="color:#c8d8f0; font-size:0.82rem;">✅ Injury risk classification</div>
            <div style="color:#c8d8f0; font-size:0.82rem;">✅ Random Forest workout level</div>
            <div style="color:#c8d8f0; font-size:0.82rem;">✅ Calorie & protein targets</div>
            <div style="color:#c8d8f0; font-size:0.82rem;">✅ ML model summary</div>
            <div style="color:#c8d8f0; font-size:0.82rem;">✅ Health disclaimer</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    if st.button("📄  GENERATE & DOWNLOAD PDF REPORT"):
        with st.spinner("Building your report..."):
            buffer = generate_pdf(u)
        if buffer:
            name = u.get("name","User").replace(" ","_")
            st.download_button(
                label="⬇️  Download PDF",
                data=buffer,
                file_name=f"FitAI_Report_{name}_{date.today()}.pdf",
                mime="application/pdf"
            )
            st.success("✅ Report generated successfully!")
        else:
            st.error("Install reportlab: py -m pip install reportlab")
